######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 14:26:50 2011
######################################################################

QT += opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CFLAGS_RELEASE = -DGL_GLEXT_PROTOTYPES -O3
QMAKE_CXXFLAGS_RELEASE = -DGL_GLEXT_PROTOTYPES -O3 -std=c++11

# Input
HEADERS += Window.h MemoryState.h Loader.h
SOURCES += main.C window.C MemoryState.C Loader.C
