######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 14:26:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CFLAGS_RELEASE = -O3
QMAKE_CXXFLAGS_RELEASE = -O3

# Input
HEADERS += Window.h MemoryState.h Loader.h
SOURCES += main.C window.C MemoryState.C Loader.C
